networks:
    base-net:
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
services:
    work:
        build:
            context: ./docker/work
            args:
                - UID=${HOST_UID}
                - GID=${HOST_GID}
                - HOST_DOCKER_GROUP_GID=${HOST_DOCKER_GROUP_GID}
        init: true
        hostname: workpace
        user: ${HOST_UID}:${HOST_GID}
        ports:
            - ${BIND_IP}:3000:3000
        volumes:
            - /var/run/docker.sock:/var/run/docker-host.sock
            - .:/workspace
        tty: true
        environment:
            TZ: ${APP_TZ}
        networks:
            - base-net